import type { ModerationCase, Community, Rule } from "@/lib/genlayer/types";

export const SEED_COMMUNITY: Community = {
  id: "arena_guild",
  owner: "0xDEMO",
  name: "Arena Guild",
  category: "GAME",
  moderationStyle: "COMPETITIVE",
  rulebookHash: "0xabc123",
  appealWindowHours: 72,
  createdAt: "2026-06-01T00:00:00Z",
};

export const SEED_RULES: Record<string, Rule> = {
  "harassment.targeted_insult": {
    id: "harassment.targeted_insult",
    title: "Targeted Harassment",
    description: "Repeated targeted insults or personal attacks directed at a specific player.",
    allowedExamples: ["General trash talk about gameplay", "Criticism of in-game decisions"],
    violationExamples: ["Repeated personal insults at one player", "Name-calling after a prior warning"],
    severityRange: ["LOW", "MEDIUM", "HIGH"],
    defaultActions: ["WARNING", "TEMP_MUTE_1H", "TEMP_MUTE_24H"],
    escalationTriggers: ["Prior warning within 30 days", "Multiple targeted players"],
    contextNotes: "Consider gaming culture norms. Distinguish competitive banter from targeted harassment.",
  },
  "conduct.griefing": {
    id: "conduct.griefing",
    title: "Griefing / Match Sabotage",
    description: "Intentionally disrupting gameplay for other players with no competitive intent.",
    allowedExamples: ["Aggressive but legitimate competitive play", "Unusual strategies that are still trying to win"],
    violationExamples: ["Team-killing own teammates", "Intentionally feeding opponents", "Match abandonment to hurt others"],
    severityRange: ["MEDIUM", "HIGH", "CRITICAL"],
    defaultActions: ["TEMP_SUSPEND_7D", "PERMANENT_BAN_REVIEW"],
    escalationTriggers: ["Repeated offence", "Coordinated with another player"],
    contextNotes: "Match clip or log required. Intent must be distinguishable from poor performance.",
  },
  "spam.off_topic": {
    id: "spam.off_topic",
    title: "Spam / Off-Topic Flooding",
    description: "Repeated irrelevant, promotional, or flooding messages in community channels.",
    allowedExamples: ["Single off-topic comment", "Promotion once in appropriate channel"],
    violationExamples: ["Repeated promotional links", "Flooding chat with repeated identical messages"],
    severityRange: ["LOW", "MEDIUM"],
    defaultActions: ["EDUCATIONAL_NOTICE", "WARNING", "CONTENT_REMOVE"],
    escalationTriggers: ["Automated or bot-like behaviour"],
    contextNotes: "Frequency and intent matter. One off-topic post is not spam.",
  },
  "exploit.use": {
    id: "exploit.use",
    title: "Exploit Use",
    description: "Using a known game exploit to gain an unfair advantage.",
    allowedExamples: ["Using advanced mechanics that are intended", "High skill techniques"],
    violationExamples: ["Known map exploit to bypass normal play", "Duplication glitch abuse"],
    severityRange: ["MEDIUM", "HIGH"],
    defaultActions: ["WARNING", "TEMP_SUSPEND_7D"],
    escalationTriggers: ["Known previously warned exploit", "Public stream showing exploit use"],
    contextNotes: "Exploit must be documented as unintended by developers.",
  },
};

export const SEED_CASES: ModerationCase[] = [
  {
    id: "case_001",
    communityId: "arena_guild",
    reporterHash: "0xreporter_a",
    reportedUserHash: "0xplayer_b",
    contentType: "GAME_CHAT",
    selectedRuleId: "harassment.targeted_insult",
    contextSummary: "A heated post-match chat. Reported player sent three targeted insults at one player after losing.",
    evidenceHashes: ["0xevid_001", "0xevid_002"],
    evidenceHash: "0xpackethash_001",
    requestedAction: "TEMP_MUTE_24H",
    priorActionSummary: "One previous warning within 30 days.",
    localeContext: "English, gaming slang, competitive match context",
    status: "RULED",
    verdict: {
      decision: "VIOLATION_FOUND",
      ruleMatched: "harassment.targeted_insult",
      severity: "MEDIUM",
      recommendedAction: "TEMP_MUTE_24H",
      confidence: 0.82,
      reasoning: "The submitted messages directly target another player with repeated insults after a warning. Evidence supports a medium-severity violation under the community rulebook.",
      statementOfReasons: {
        policyBasis: "Rule: harassment.targeted_insult — Targeted Harassment",
        factsConsidered: ["Three targeted insults in post-match chat", "Prior warning within 30 days", "Single target player"],
        whyActionIsProportional: "A temporary mute is proportionate because the behaviour was repeated but not severe enough for suspension.",
        appealAvailable: true,
      },
      safetyFlags: [],
      consistencyNotes: "Similar prior cases used warning or short mute depending on repetition. This case includes prior warning, supporting temporary mute.",
      reviewedAt: "2026-06-10T14:22:00Z",
    },
    submittedAt: "2026-06-10T13:00:00Z",
    submittedBy: "0xmod_001",
    packet: {
      caseId: "case_001",
      communityId: "arena_guild",
      rulebookVersion: "v1.0.0",
      reportedUserHash: "0xplayer_b",
      reporterHash: "0xreporter_a",
      contentType: "GAME_CHAT",
      selectedRuleId: "harassment.targeted_insult",
      reportedContentExcerpt: "[REDACTED — evidence hash committed]",
      contextSummary: "A heated post-match chat. Reported player sent three targeted insults at one player after losing.",
      priorActionSummary: "One previous warning within 30 days.",
      evidenceHashes: ["0xevid_001", "0xevid_002"],
      requestedAction: "TEMP_MUTE_24H",
      localeContext: "English, gaming slang, competitive match context",
      submittedAt: "2026-06-10T13:00:00Z",
    },
  },
  {
    id: "case_002",
    communityId: "arena_guild",
    reporterHash: "0xreporter_c",
    reportedUserHash: "0xplayer_d",
    contentType: "MATCH_LOG",
    selectedRuleId: "conduct.griefing",
    contextSummary: "Ranked match. Player intentionally fed opponents in final round after team disagreement. Three deaths in under 90 seconds.",
    evidenceHashes: ["0xevid_003"],
    evidenceHash: "0xpackethash_002",
    requestedAction: "TEMP_SUSPEND_7D",
    priorActionSummary: "No prior record.",
    localeContext: "English, ranked competitive",
    status: "SUBMITTED",
    submittedAt: "2026-06-12T09:15:00Z",
    submittedBy: "0xmod_002",
    packet: {
      caseId: "case_002",
      communityId: "arena_guild",
      rulebookVersion: "v1.0.0",
      reportedUserHash: "0xplayer_d",
      reporterHash: "0xreporter_c",
      contentType: "MATCH_LOG",
      selectedRuleId: "conduct.griefing",
      reportedContentExcerpt: "[REDACTED — evidence hash committed]",
      contextSummary: "Ranked match. Player intentionally fed opponents in final round after team disagreement.",
      priorActionSummary: "No prior record.",
      evidenceHashes: ["0xevid_003"],
      requestedAction: "TEMP_SUSPEND_7D",
      localeContext: "English, ranked competitive",
      submittedAt: "2026-06-12T09:15:00Z",
    },
  },
  {
    id: "case_003",
    communityId: "arena_guild",
    reporterHash: "0xreporter_e",
    reportedUserHash: "0xplayer_f",
    contentType: "FORUM_POST",
    selectedRuleId: "spam.off_topic",
    contextSummary: "User posted 12 identical promotional messages across 4 channels in under an hour.",
    evidenceHashes: ["0xevid_004", "0xevid_005"],
    evidenceHash: "0xpackethash_003",
    requestedAction: "CONTENT_REMOVE",
    priorActionSummary: "No prior record.",
    localeContext: "English, community forum",
    status: "RULED",
    verdict: {
      decision: "VIOLATION_FOUND",
      ruleMatched: "spam.off_topic",
      severity: "LOW",
      recommendedAction: "CONTENT_REMOVE",
      confidence: 0.91,
      reasoning: "12 identical messages across 4 channels in under an hour constitutes clear spam behaviour under the off-topic flooding rule.",
      statementOfReasons: {
        policyBasis: "Rule: spam.off_topic — Spam / Off-Topic Flooding",
        factsConsidered: ["12 identical messages", "4 different channels", "Under 1 hour"],
        whyActionIsProportional: "Content removal is appropriate for first-offence spam. Educational notice accompanies the removal.",
        appealAvailable: true,
      },
      safetyFlags: [],
      consistencyNotes: "Consistent with prior spam decisions. First offence treated as content removal plus notice.",
      reviewedAt: "2026-06-11T11:00:00Z",
    },
    submittedAt: "2026-06-11T10:00:00Z",
    submittedBy: "0xmod_001",
    packet: {
      caseId: "case_003",
      communityId: "arena_guild",
      rulebookVersion: "v1.0.0",
      reportedUserHash: "0xplayer_f",
      reporterHash: "0xreporter_e",
      contentType: "FORUM_POST",
      selectedRuleId: "spam.off_topic",
      reportedContentExcerpt: "[REDACTED — evidence hash committed]",
      contextSummary: "User posted 12 identical promotional messages across 4 channels in under an hour.",
      priorActionSummary: "No prior record.",
      evidenceHashes: ["0xevid_004", "0xevid_005"],
      requestedAction: "CONTENT_REMOVE",
      localeContext: "English, community forum",
      submittedAt: "2026-06-11T10:00:00Z",
    },
  },
];
